### ISSUE TITLE
[task] Propulsion Slot differentiation

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/Endless-Sky-Delta#87]
### Problem Description

Most ships in the game are limited to 1 of each kind of slot.

### Related Issue Links

various discussions.

### Desired Solution

Go through all the ships and identify ships that are particularly noteworthy in terms of one or more of its maneuverability elements. These are ships who, by design or luck, are ships that *in the lore* or *in the lore that we want the game to have* are special. Maybe it's an SR-71 racer that is more or less average, except it is noted for it's ability to go fast. Maybe it's an acrobatics plane that has average speed/acceleration, but great agility.

The intent, at the end of the day, is that while a single slot is the "norm" for each slot, there should be a variety of ships that have more slots of a particular type. The engine variants of the Kestrel and the Marauder ships are a case in point of ships that should have additional slots. These engine variants should probably have +1 slot of each type.

Overall, there should be three general categories for ships:

1. Regular ships (1 slot of each)
2. Specialty capability (+1 slot in one or two of the propulsion types)
3. Overall exceptional capability (+1 of most or all propulsion types)

Noting that it is definitely possible for ships to be both 2 & 3, but this should be rare.

### Alternative Approaches

?

### Additional Context

This is an ongoing effort to see if it is a real possibility of making ships more unique so that two ships with similar size, mass, and engine space could nontheless have a meaningful difference that players can use to pick between different ships depending on their priorities.

I would also like to note that I intend to do this. Sooner, probably, since this has come up again recently. I welcome people contributing ideas to it, though. Likewise, if you have different ideas for how ships can be differentiated in terms of mobility at the hull level, I'm happy to hear them.
```[tasklist]
### Tasks
- [ ] https://github.com/endless-sky/Endless-Sky-Delta/pull/86
- [x] Marauder ships
- [x] Kestrel engine variant
- [x] Human ships in general
- [x] Hai ships in general
- [x] Alien ships in general
```

**Comment by TheGiraffe3** [comment]
So you're saying just give each Marauder Engines ship an extra slot of each variety? I could do that.

**Comment by Zitchas** [comment]
Yep, that's exactly what I'm saying. The Engine variant of the Kestrel, too, if it's still at 1 across the set.

**Comment by Zitchas** [comment]
I'm perfectly happy to have it go piecemeal, too. It doesn't have to be all the ships at once or anything.

**Comment by Zitchas** [comment]
A general comment on the slot system as well: Another benefit to having slots is that it increases the likelyhood that a ship's engine space still has some space available in it. I would like to see a healthy ecosystem of mod outfits that make use of this space. Things that almost certainly can't compete with the benefit of *"more engines"*, but if more engines isn't an option, could be quite interesting or useful. Perhaps niche benefits. Including new mechanics that aren't in game yet.

Percentile based modifiers. Having an outfit that, say, makes whatever engine it is installed along more efficient in terms of energy. Or heat. Or perhaps a high tier faction might have a means of reducing mass a bit. or increasing it! I'd certainly be up for, say, a framework mod that takes up a bunch of engine space but adds a thruster slot for those that really like the advantages that small engines will hopefully eventually have, even if they don't have the sheer thrust that a big engine has. It'd have to be a significant space cost, though. Of course, afterburners are an obvious thing to have take up this space, but I'm sure there are a lot of other ideas for engine-modifying effects out there.

**Comment by Zitchas** [comment]
While there is still some room to tweak specialized ships, I think this is largely closed. More innovation in terms of outfits and mods to modify and alter engine performance are welcome.
